### ISSUE TITLE
Strange behavior while using aliases - Could not load mock [Namespace\ClassName], class already exists

### ISSUE THREAD

**Issue by kwn** [padraic/mockery#473]
Hi

I've got a very strange problem while trying to use mock alias. I want to create an alias mock for a class with only two simple static getters. When I'm trying to create alias mock I've got an exception: ```Could not load mock [My\Namespace\ClassName], class already exists```. Well, indeed, the class exists. It's loaded by composer's autoloader before running a test suite.

Just want to explain my environment. Everything is very simple. I'm using mockery (0.9.4) with phpunit (4.6.6). My phpunit.xml config file looks like that:

```xml
<phpunit bootstrap="vendor/autoload.php" colors="true" verbose="true">
    <testsuites>
        <testsuite name="Number to string tests">
            <directory>tests/</directory>
        </testsuite>
    </testsuites>
    <filter>
        <whitelist>
            <directory suffix=".php">src/</directory>
        </whitelist>
    </filter>
    <listeners>
        <listener class="\Mockery\Adapter\Phpunit\TestListener"/>
    </listeners>
    <logging>
        <log type="coverage-text" target="php://stdout" lowUpperBound="50" highLowerBound="80"/>
        <log type="coverage-html" target="build/logs/coverage" charset="UTF-8" highlight="true" lowUpperBound="50" highLowerBound="80"/>
        <log type="coverage-clover" target="build/logs/clover.xml"/>
    </logging>
</phpunit>
```

I'm creating a standalone library. I'm using composer with PSR-4. I've got a couple of tests, and I'm using Mockery only one (while trying to create this alias). My test class looks like that:

```php
<?php

namespace Kwn\NumberToWords\Language\Polish\Transformer\Decorator;

use Mockery as m;
use Kwn\NumberToWords\Language\Polish\Transformer\NumberTransformer;
use Kwn\NumberToWords\Model\Currency;
use Kwn\NumberToWords\Model\Number;

class CurrencyTransformerDecoratorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @expectedException \Kwn\NumberToWords\Exception\InvalidArgumentException
     */
    public function testConstructorThrowsExceptionWithUnknownCurrency()
    {
        new CurrencyTransformerDecorator(
            new NumberTransformer(),
            new Currency('UNK'),
            CurrencyTransformerDecorator::FORMAT_SUBUNITS_IN_WORDS
        );
    }

    /**
     * @expectedException \Kwn\NumberToWords\Exception\InvalidArgumentException
     */
    public function testConstructorThrowsExceptionWithUnknownSubunitsCurrency()
    {
        $dictionary = m::mock('alias:Kwn\NumberToWords\Language\Polish\Dictionary\Currency');
        $dictionary->shouldReceive('getSubunits')->andReturn([]);

        new CurrencyTransformerDecorator(
            new NumberTransformer(),
            new Currency('PLN'),
            CurrencyTransformerDecorator::FORMAT_SUBUNITS_IN_WORDS
        );
    }

    /**
     * @expectedException \Kwn\NumberToWords\Exception\InvalidArgumentException
     */
    public function testConstructorThrowsExceptionWithUnknownSubunitsFormat()
    {
        new CurrencyTransformerDecorator(
            new NumberTransformer(),
            new Currency('PLN'),
            10
        );
    }

    public function testTransformMoneyUnits()
    {
        $transformer = new CurrencyTransformerDecorator(
            new NumberTransformer(),
            new Currency('PLN'),
            CurrencyTransformerDecorator::FORMAT_SUBUNITS_IN_WORDS
        );

        $this->assertEquals('jeden złoty zero groszy', $transformer->toWords(new Number(1)));
        $this->assertEquals('dwa złote zero groszy', $transformer->toWords(new Number(2)));
        $this->assertEquals('pięć złotych zero groszy', $transformer->toWords(new Number(5)));
        $this->assertEquals('pięćset czterdzieści jeden złotych zero groszy', $transformer->toWords(new Number(541)));
        $this->assertEquals('pięćset czterdzieści dwa złote zero groszy', $transformer->toWords(new Number(542)));
        $this->assertEquals('pięćset czterdzieści cztery złote zero groszy', $transformer->toWords(new Number(544)));
        $this->assertEquals('pięćset czterdzieści pięć złotych zero groszy', $transformer->toWords(new Number(545)));
    }

// [...] other tests
```

So the only one place (in the whole test suite) that the Mockery is used is that second test (```testConstructorThrowsExceptionWithUnknownSubunitsCurrency()```). I get a RuntimeException (thrown in ```Mockery\Container``` near line 215). I completely don't understand how to use Mockery's alias functionality in pair with composer's autoloader that loads all classes before a test.

I've tried to run this test in a separate phpunit process, but I've got the same error. Removing ```@expectedException``` annotation doesn't change anything. Still got an error. Any ideas? Maybe I don't understand how the alias works? Full stack trace below:

```
....F...............

Time: 303 ms, Memory: 8.00Mb

There was 1 failure:

1) Kwn\NumberToWords\Language\Polish\Transformer\Decorator\CurrencyTransformerDecoratorTest::testConstructorThrowsExceptionWithUnknownSubunitsCurrency
Failed asserting that exception of type "Mockery\Exception\RuntimeException" matches expected exception "\Kwn\NumberToWords\Exception\InvalidArgumentException". Message was: "Could not load mock Kwn\NumberToWords\Language\Polish\Dictionary\Currency, class already exists" at
#0 [internal function]: Mockery\Container->mock('alias:Kwn\Numbe...')
#1 /home/kwnuk/Repositories/number-to-words/vendor/mockery/mockery/library/Mockery.php(74): call_user_func_array(Array, Array)
#2 /home/kwnuk/Repositories/number-to-words/tests/Language/Polish/Transformer/Decorator/CurrencyTransformerDecoratorTest.php(29): Mockery::mock('alias:Kwn\Numbe...')
#3 [internal function]: Kwn\NumberToWords\Language\Polish\Transformer\Decorator\CurrencyTransformerDecoratorTest->testConstructorThrowsExceptionWithUnknownSubunitsCurrency()
#4 /home/kwnuk/Repositories/number-to-words/vendor/phpunit/phpunit/src/Framework/TestCase.php(866): ReflectionMethod->invokeArgs(Object(Kwn\NumberToWords\Language\Polish\Transformer\Decorator\CurrencyTransformerDecoratorTest), Array)
#5 /home/kwnuk/Repositories/number-to-words/vendor/phpunit/phpunit/src/Framework/TestCase.php(743): PHPUnit_Framework_TestCase->runTest()
#6 /home/kwnuk/Repositories/number-to-words/vendor/phpunit/phpunit/src/Framework/TestResult.php(609): PHPUnit_Framework_TestCase->runBare()
#7 /home/kwnuk/Repositories/number-to-words/vendor/phpunit/phpunit/src/Framework/TestCase.php(699): PHPUnit_Framework_TestResult->run(Object(Kwn\NumberToWords\Language\Polish\Transformer\Decorator\CurrencyTransformerDecoratorTest))
#8 /home/kwnuk/Repositories/number-to-words/vendor/phpunit/phpunit/src/Framework/TestSuite.php(722): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#9 /home/kwnuk/Repositories/number-to-words/vendor/phpunit/phpunit/src/Framework/TestSuite.php(722): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#10 /home/kwnuk/Repositories/number-to-words/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(406): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#11 /home/kwnuk/Repositories/number-to-words/vendor/phpunit/phpunit/src/TextUI/Command.php(153): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#12 /home/kwnuk/Repositories/number-to-words/vendor/phpunit/phpunit/src/TextUI/Command.php(105): PHPUnit_TextUI_Command->run(Array, true)
#13 /home/kwnuk/Repositories/number-to-words/vendor/phpunit/phpunit/phpunit(36): PHPUnit_TextUI_Command::main()
#14 {main}.

FAILURES!
Tests: 20, Assertions: 67, Failures: 1.
```

**Comment by davedevelopment** [comment]
How is it being loaded through the autoloader? PSR0/4, classmap or file include? The alias mechanism requires that the class hasn't been defined already, so you need to prevent that from happening. This is usually done by having composer autoload the class when some code requires it and further so by running all tests that do use the class in a separate process.

Does it still fail if you run

```
phpunit --filter testConstructorThrowsExceptionWithUnknownSubunitsCurrency

```

?

**Comment by kwn** [comment]
@davedevelopment 
Hi Dave, thanks for a response. It's beeing loaded through psr4

```
    "autoload": {
        "psr-4": {
            "Kwn\\NumberToWords\\": "src"
        }
    }
```

I've tested with ```--filter``` option and it works fine, test passes. So is there any method to "isolate" that test somehow?

**Comment by robertbasic** [comment]
Try running the test in a separate process. Take a look at the Mocking Hard Dependencies in the cookbook http://docs.mockery.io/en/latest/cookbook/mocking_hard_dependencies.html

**Comment by davedevelopment** [comment]
Yes, use the `@runTestsInSeparateProcesses` in that test class as a starter, but you may need to evaluate the whole test suite. If your tests use `Kwn\NumberToWords\Language\Polish\Dictionary\Currency` anywhere else, those tests would also have to run in isolation.
