### ISSUE TITLE
Exception report with mockery isn't friendly

### ISSUE THREAD

**Issue by peixinchen** [padraic/mockery#624]
```
There was 1 error:

1) SomeTestCase::testMethod
PHPUnit_Framework_Exception: [Exception]
  Serialization of 'Closure' is not allowed

Caused by
exception 'ErrorException' with message 'unserialize(): Error at offset 0 of 186 bytes' in phar:///<path of phpunit>/phpunit/phpunit/Util/PHP.php:114
```

If I got a mistake, the report always like this, and I could not understand what happend? So do I have a better way to solved this?

**Comment by davedevelopment** [comment]
Try turning `backupGlobals` and `backupStaticAttributes` to false in your PHPUnit configuration?

**Comment by peixinchen** [comment]
We turn off these two options, but it seems that the options doesn't work as expectation.
```php
/**
 *
 * @runTestsInSeparateProcesses
 * @preserveGlobalState disabled
 * @backupGlobals disabled
 * @backupStaticAttributes disabled
 */
class MyTest extends TestCase
{
    /**
     * @after
     */
    public function tearDown()
    {
        Mockery::close();
    }
 
    public function testExample()
    {
        ...
    }
}
```

And the test result likes below.
```
1) MyTest::testExample
PHPUnit_Framework_Exception: [Exception]
  Serialization of 'Closure' is not allowed

Caused by
exception 'ErrorException' with message 'unserialize(): Error at offset 0 of 186 bytes' in phar://{{ path of php }}/bin/phpunit/phpunit/Util/PHP.php:114
Stack trace:
#0 [internal function]: PHPUnit_Util_PHP->{closure}(8, 'unserialize(): ...', 'phar:///home/wo...', 114, Array)
#1 phar://{{ path of php }}/bin/phpunit/phpunit/Util/PHP.php(114): unserialize('\n              ...')
#2 phar://{{ path of php }}/bin/phpunit/phpunit/Util/PHP.php(52): PHPUnit_Util_PHP->processChildResult(Object(C2IntentPushTest), Object(PHPUnit_Framework_TestResult), '\n              ...', '')
#3 phar://{{ path of php }}/bin/phpunit/phpunit/Framework/TestCase.php(722): PHPUnit_Util_PHP->runTestJob('<?php\nif (!defi...', Object(MyTest), Object(PHPUnit_Framework_TestResult))
#4 phar://{{ path of php }}/bin/phpunit/phpunit/Framework/TestSuite.php(747): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#5 phar://{{ path of php }}/bin/phpunit/phpunit/Framework/TestSuite.php(747): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#6 phar://{{ path of php }}/bin/phpunit/phpunit/TextUI/TestRunner.php(440): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#7 phar://{{ path of php }}/bin/phpunit/phpunit/TextUI/Command.php(149): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#8 phar://{{ path of php }}/bin/phpunit/phpunit/TextUI/Command.php(100): PHPUnit_TextUI_Command->run(Array, true)
#9 {{ path of php }}/bin/phpunit(545): PHPUnit_TextUI_Command::main()
#10 {main}

```

PS: This is my phpunit.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         bootstrap="bootstrap/app.php"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="true"
         syntaxCheck="false">
    <testsuites>
        <testsuite name="Application Test Suite">
            <directory suffix="Test.php">./tests</directory>
        </testsuite>
    </testsuites>
    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">./app</directory>
            <exclude>
                <file>./app/Http/routes.php</file>
            </exclude>
        </whitelist>
    </filter>
    <php>
        <env name="APP_ENV" value="testing"/>
        <env name="CACHE_DRIVER" value="array"/>
    </php>
</phpunit>
```

**Comment by davedevelopment** [comment]
No idea. Maybe try putting `@preserveGlobalState disabled` on the test case itself, rather than the class?

**Comment by robertbasic** [comment]
@peixinchen could you please provide the test and the code you're testing as well? Thanks!

**Comment by bytestream** [comment]
I fixed this by doing the following in `tearDown()`
````php
Mockery::close();
Mockery::setGenerator(Mockery::getDefaultGenerator());
````
I believe the issue was that the `CachingGenerator` was caching previous mocks, and some code was mocking an object which was later serialized and lead to this issue
